### ISSUE TITLE
[How-to] Download an email body text and attachments

### ISSUE THREAD

**Issue by raszkiewicz** [afterlogic/MailSo#2]
I want to download an email body text and attachments using MailSo library, possible using message IDs,

My question are:

- is it possible to do that with the MailSo library?
- is there a way to get the whole inbox in XML format using the MailSo library?

The goal is to let external application read part of an email body text, download attachments and attach files to created message.

**Comment by afterlogic-support** [comment]
Yes it's possible to achieve that using MailSo. Our WebMail Lite application is using MailSo internally, and it might be easier to use Web API of WebMail Lite rather than deal with low-level programming of email operations.

Please see the following documentation section for details: https://afterlogic.com/docs/webmail-lite/integration-and-development/web-api#webapimethods

This section deals with receiving mail: https://afterlogic.com/docs/webmail-lite/integration-and-development/web-api/receiving-mail
